<div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-title">
                        <span class="icon"><i class="icon-th"></i></span>
                        <h5>Desperdicios de Caña</h5>
                        <div class="buttons">
                            <a href="<?php echo BASE_URL?>desperdicio/upload" class="btn btn-mini btn-success"><i class="icon-hdd"></i> Subir Archivo</a>
                            <button id="btnexport" class="btn btn-mini btn-success"><i class="icon-download-alt"></i> Exportar</button>
                            <a href="<?php echo BASE_URL?>desperdicio/download" class="btn btn-mini btn-success"><i class="icon-download-alt"></i> Descargar PDF</a>
                            <a href="<?php echo BASE_URL?>desperdicio/nuevo" class="btn btn-mini btn-success"><i class="icon-plus"></i> Añadir</a>
                        </div>
                    </div>
                    <?php if(isset($this->desperdicio)&& count($this->desperdicio)):?>
                    <div class="widget-content nopadding">
                        <table class="table table-bordered data-table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Dia</th>
                                <th>Máquina</th>
                                <th>Operador</th>
                                <th>Turno</th>
                                <th>Finca</th>
                                <th>Variedad</th>
                                <th>Tocones</th>
                                <th>Caña Larga</th>
                                <th>Caña Picada</th>
                                <th>Puntas</th>
                                <th>Rendimiento</th>
                            </tr>
                            </thead>
                            <?php for($i=0;$i<count($this->desperdicio);$i++):?>
                                <tbody>
                                <tr class="gradeX">
                                    <td><?php echo $this->desperdicio[$i]['idcaptura'];?></td>
                                    <td><?php echo $this->desperdicio[$i]['dia'];?></td>
                                    <td><?php echo $this->desperdicio[$i]['maquina_nombre'];?></td>
                                    <td class="center"><?php echo $this->desperdicio[$i]['operador_nombre'];?></td>
                                    <td class="center"><?php echo $this->desperdicio[$i]['turno'];?></td>
                                    <td class="center"><?php echo $this->desperdicio[$i]['finca_nombre'];?></td>
                                    <td class="center"><?php echo $this->desperdicio[$i]['variedad_nombre'];?></td>
                                    <td class="center"><?php echo $this->desperdicio[$i]['tocones'];?></td>
                                    <td class="center"><?php echo $this->desperdicio[$i]['cana_larga'];?>  </td>
                                    <td class="center"><?php echo $this->desperdicio[$i]['cana_picada'];?>  </td>
                                    <td class="center"><?php echo $this->desperdicio[$i]['puntas'];?>  </td>
                                    <td class="center"><?php echo $this->desperdicio[$i]['rendimiento'];?>  </td>
                                </tr>
                                </tbody>
                            <?php endfor;?>
                        </table>
                        <?php else:?>
                            <h5>No hay datos para mostrar.</h5>
                        <?php endif;?>
                    </div>
                </div>
            </div>
        </div>