<div class="span6">
    <div class="widget-box">
        <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
            <h5>Form Elements</h5>
        </div>
        <div class="widget-content nopadding">
            <form action="#" method="get" class="form-horizontal">
                <div class="control-group">
                    <label class="control-label">Día</label>
                    <div class="controls">
                        <select >
                            <?php for($i=1;$i<126;$i++):?>
                                <option><?php echo $i;?></option>
                            <?php endfor;?>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Máquina</label>
                    <div class="controls">
                        <select >
                            <option>36 C 3500 Llanta<option/>
                            <option>37 C3510 Oruga<option/>
                            <option>38 JD 3520 Oruga<option/>
                            <option>39 C3500 Llanta<option/>
                            <option>40 JD3510 Llanta<option/>
                            <option>41 C 3510 Llanta<option/>
                            <option<42 C 3500 Llanta<option/>
                            <option>43 JD 3520 Oruga<option/>
                            <option>44 JD 3520 Oruga<option/>
                            <option>45 JD 3510 Oruga<option/>
                            <option>46 JD 3520 Llanta<option/>
                            <option>Corta Manual<option/>

                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Operador</label>
                    <div class="controls">
                        <select >
                            <option>Alberto Cortes</option>
                            <option>Alonso Gomez</option>
                            <option>Alvaro Cerdas</option>
                            <option>Ariel Carvajal</option>
                            <option>Bryan Calderon</option>
                            <option>Carlos Barrantes</option>
                            <option>César Obando </option>
                            <option>Cristhian Obando</option>
                            <option>Eladio Prieto</option>
                            <option>Eric Sequeira</option>
                            <option>Gerardo Carmona</option>
                            <option>Guillermo Aguirre</option>
                            <option>Gustavo Marchena</option>
                            <option>Hector Lopez</option>
                            <option>Jorge Cascante</option>
                            <option>Juan Carlos Vargas</option>
                            <option>Leonardo Miranda</option>
                            <option>Mario Miranda</option>
                            <option>Norberto Cerrano</option>
                            <option>Oscar Chavarria</option>
                            <option>Rafael Alvarez</option>
                            <option>Tony Rodriguez</option>
                            <option>Operador 1 </option>
                            <option>Operador 2</option>

                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Turno</label>
                    <div class="controls">
                        <select >
                            <option>First option</option>
                            <option>Second option</option>
                            <option>Third option</option>
                            <option>Fourth option</option>
                            <option>Fifth option</option>
                            <option>Sixth option</option>
                            <option>Seventh option</option>
                            <option>Eighth option</option>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Finca</label>
                    <div class="controls">
                        <select >
                            <option>Bambu </option>
                            <option>Bambuzal</option>
                            <option>Basurero</option>
                            <option>Carrizal</option>
                            <option>Casa Amarilla</option>
                            <option>Chomes</option>
                            <option>Delicias</option>
                            <option>El Cambio</option>
                            <option>El Carao</option>
                            <option>El Cinco</option>
                            <option>El Cocal</option>
                            <option>El Dinarte</option>
                            <option>El Escondido</option>
                            <option>El Espabel</option>
                            <option>El Galeron</option>
                            <option>El Molino</option>
                            <option>El Paraiso</option>
                            <option>El Sueño</option>
                            <option>El Uno</option>
                            <option>Embarcadero</option>
                            <option>Encanto</option>
                            <option>La Flor</option>
                            <option>La Gloria</option>
                            <option>La Gloria</option>
                            <option>La Grama</option>
                            <option>La Laguna</option>
                            <option>La Montaña</option>
                            <option>La Papaya</option>
                            <option>La Pineda</option>
                            <option>La Pineda</option>
                            <option>La Zoila</option>
                            <option>Lagunilla</option>
                            <option>Las Manzanas</option>
                            <option>Las Traistezas</option>
                            <option>Laurelar</option>
                            <option>Los Coyotes</option>
                            <option>Los Negros</option>
                            <option>Matamoros</option>
                            <option>MM Centro</option>
                            <option>MM Vivero</option>
                            <option>Naranjito</option>
                            <option>Palermo</option>
                            <option>Palermo</option>
                            <option>Pitahaya</option>
                            <option>Pta Plancha</option>
                            <option>Potrerito</option>
                            <option>San Francisco</option>
                            <option>Santa Emilia</option>
                            <option>Sardinal</option>
                            <option>Sardinal</option>
                            <option>Tronconal</option>
                            <option>Yoyo</option>
                            <option>ZonaFranca</option>

                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Variedad</label>
                    <div class="controls">
                        <select >
                            <option>B82-333<option/>
                            <option>CP14-1586<option/>
                            <option>CP72-1210<option/>
                            <option>CP72-2086<option/>
                            <option>CP80-1743<option/>
                            <option>Laica07-309<option/>
                            <option>Laica01-307<option/>
                            <option>RB86-7515<option/>
                            <option>SP81-3250<option/>
                            <option>Varias<option/>

                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Tocones</label>
                    <div class="controls">
                        <input type="text" name="mTocones" onKeyPress="if (event.keyCode < 46 || event.keyCode > 57 )event.returnValue = false;"/>

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Caña Larga</label>
                    <div class="controls">
                        <input type="text" name="mCañaL" onKeyPress="if (event.keyCode < 46 || event.keyCode > 57 )event.returnValue = false;"/>

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Caña Picada</label>
                    <div class="controls">
                        <input type="text" name="mCañaPic" onKeyPress="if (event.keyCode < 46 || event.keyCode > 57 )event.returnValue = false;"/>

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Puntas</label>
                    <div class="controls">
                        <input type="text" name="mPuntas" onKeyPress="if (event.keyCode < 46 || event.keyCode > 57 )event.returnValue = false;"/>

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Rendimiento</label>
                    <div class="controls">

                        <input type="text" name="mRendimiento" onKeyPress="if (event.keyCode < 46 || event.keyCode > 57 )event.returnValue = false;"/>
                    </div>
                </div>


                <div class="form-actions">
                    <div class="buttons"><a href="<?php echo BASE_URL?>#" class="btn btn-mini btn-success"><i class="icon-plus"></i> Añadir</a></div>

                    <!--button type="submit" class="btn btn-success">Save</button-->
                </div>
            </form>
        </div>
    </div>
</div>

