<div class="container-fluid">
    <div class="row-fluid">
        <div class="span6">
    <div class="widget-box">
        <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
            <h5>Form Elements</h5>
        </div>
        <div class="widget-content nopadding">
            <form id="frmAddCaptura" class="form-horizontal" method="post"  action="<?php echo BASE_URL?>desperdicio/nuevo">
                <input type="hidden"name="guardar" value="1"/>
                <div class="control-group">
                      <label class="control-label">Día</label>
                              <div class="controls">
                        <select id="mDia" name="mDia">
                            <?php for($i=1;$i<126;$i++):?>
                                <option><?php echo $i;?></option>
                            <?php endfor;?>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Máquina</label>
                         <div class="controls">
                             <select id="mMaquina" name="mMaquina">
                                 <?php if(isset($this->maquinas)&& count($this->maquinas)):?>
                                     <?php for($i=0;$i<count($this->maquinas);$i++):?>
                                         <option  value="<?php echo $this->maquinas[$i]['id'];?>"><?php echo $this->maquinas[$i]['nombre'];?></option>
                                     <?php endfor;?>
                                 <?php endif;?>
                             </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Operador</label>
                    <div class="controls">
                        <select id="mOperador" name="mOperador">
                            <?php if(isset($this->operador)&& count($this->operador)):?>
                                <?php for($i=0;$i<count($this->operador);$i++):?>
                                    <option  value="<?php echo $this->operador[$i]['int'];?>"><?php echo $this->operador[$i]['nombres'];?></option>
                                <?php endfor;?>
                            <?php endif;?>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Turno</label>
                    <div class="controls">
                        <select id="mTurno" name="mTurno">
                            <?php for($i=1;$i<6;$i++):?>
                                <option value="<?php echo $i;?> "><?php echo $i;?></option>
                            <?php endfor;?>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Finca</label>
                    <div class="controls">
                        <select id="mFinca" name="mFinca">
                            <?php if(isset($this->fincas)&& count($this->fincas)):?>
                                <?php for($i=0;$i<count($this->fincas);$i++):?>
                                    <option  value="<?php echo $this->fincas[$i]['id'];?>"><?php echo $this->fincas[$i]['nombre'];?></option>
                                <?php endfor;?>
                            <?php endif;?>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Variedad</label>
                    <div class="controls">
                        <select id="mFinca" name="mVariedad">
                            <?php if(isset($this->variedad)&& count($this->variedad)):?>
                                <?php for($i=0;$i<count($this->variedad);$i++):?>
                                    <option  value="<?php echo $this->variedad[$i]['id'];?>"><?php echo $this->variedad[$i]['nombre'];?></option>
                                <?php endfor;?>
                            <?php endif;?>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Tocones</label>
                    <div class="controls">
                        <input type="number" min="0" step="0.01"name="mTocones" value="<?php if (isset($this->datos['mTocones'])) echo $this->datos['mTocones']; ?>"/>

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Caña Larga</label>
                    <div class="controls">
                        <input type="number" min="0" step="0.01" name="mCañaL" value="<?php if (isset($this->datos['mCañal'])) echo $this->datos['mCañal']; ?>"/>

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Caña Picada</label>
                    <div class="controls">
                        <input type="number" min="0" step="0.01" name="mCañaPic" value="<?php if (isset($this->datos['mCañaPic'])) echo $this->datos['mCañaPic']; ?>"/>

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Puntas</label>
                    <div class="controls">
                        <input type="number" min="0" step="0.01" name="mPuntas" value="<?php if (isset($this->datos['mPuntas'])) echo $this->datos['mPuntas']; ?>"/>

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Rendimiento</label>
                    <div class="controls">
                        <input type="number" min="0" step="0.01" name="mRendimiento" value="<?php if (isset($this->datos['mRendimiento'])) echo $this->datos['mRendimiento']; ?>"/>
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-success">Ingresar Datos</button>
                    <button type="button" class="btn btn-danger">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
</div>
    </div>
</div>

