<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"><i class="icon-th"></i></span>
                    <h5>Materia Extraña</h5>
                    <div class="buttons">
                        <a href="<?php echo BASE_URL?>materia/upload" class="btn btn-mini btn-success"><i class="icon-hdd"></i> Subir Archivo</a>
                        <button id="btnexport" class="btn btn-mini btn-success"><i class="icon-download-alt"></i> Exportar</button>
                        <a href="<?php echo BASE_URL?>materia/download" class="btn btn-mini btn-success"><i class="icon-download-alt"></i> Descargar PDF</a>
                        <a href="<?php echo BASE_URL?>materia/nuevo" class="btn btn-mini btn-success"><i class="icon-plus"></i> Añadir</a>
                    </div>
                </div>
                <?php if(isset($this->materias)&& count($this->materias)):?>
                <div class="widget-content nopadding">
                    <table class="table table-bordered data-table">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Dia</th>
                            <th>Maquina</th>
                            <th>Operador</th>
                            <th>Finca</th>
                            <th>Variedad</th>
                            <th>Peso</th>
                            <th>Cepa</th>
                            <th>Hojas</th>
                            <th>Tierra</th>
                            <th>Cogollo</th>
                        </tr>
                        </thead>
                        <?php for($i=0;$i<count($this->materias);$i++):?>
                            <tbody>
                            <tr class="gradeX">
                                <td><?php echo $this->materias[$i]['idmateria'];?></td>
                                <td><?php echo $this->materias[$i]['dia'];?></td>
                                <td><?php echo $this->materias[$i]['maquina_nombre'];?></td>
                                <td class="center"><?php echo $this->materias[$i]['operador_nombre'];?></td>
                                <td class="center"><?php echo $this->materias[$i]['finca_nombre'];?></td>
                                <td class="center"><?php echo $this->materias[$i]['variedad_nombre'];?></td>
                                <td class="center"><?php echo $this->materias[$i]['cogollo'];?></td>
                                <td class="center"><?php echo $this->materias[$i]['cepa'];?></td>
                                <td class="center"><?php echo $this->materias[$i]['verdes'];?>  </td>
                                <td class="center"><?php echo $this->materias[$i]['tierra'];?></td>
                                <td class="center"><?php echo $this->materias[$i]['secas'];?>  </td>

                            </tr>
                            </tbody>
                        <?php endfor;?>
                    </table>
                    <?php else:?>
                        <h5>No hay datos para mostrar.</h5>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>