<div class="container-fluid" style="background-image: url("public/img/background.JPG)">
<div class="row-fluid">
    <h1><?php if($this->mensaje) echo $this->mensaje;?></h1>
    <div class="quick-actions_homepage">
        <ul class="quick-actions">
            <?php if(!Sessions::get('autenticado')):?>
            <ul class="quick-actions">
                <li> <a href="<?php echo BASE_URL.'login'?>"> <i class="icon-repeat"></i> Iniciar Sesión </a> </li>
            </ul>
            <?php endif;?>
        </ul>
    </div>
</div>
</div>