<div class="container-fluid" style="background-image: url("public/img/background.JPG)">
    <div class="row-fluid">
        <h1><?php if($this->mensaje) echo $this->mensaje;?></h1>
        <div class="quick-actions_homepage">
            <ul class="quick-actions">
                <li> <a href="<?php echo BASE_URL?>"> <i class="icon-repeat"></i> Regresar </a> </li>
            </ul>
        </div>
    </div>
</div>