<!--begin home-section-->
<div class="row-fluid">
    <div class="quick-actions_homepage">
           <a href="<?php echo BASE_URL.'rendimiento'?>" class="btn btn-warning btn-large"> <i class="icon-globe"></i> Fincas </a>
           <a href="<?php echo BASE_URL.'configuracion/maquinas'?>" class="btn btn-warning btn-large"> <i class="icon-screenshot"></i> Maquinas</a>
           <a href="<?php echo BASE_URL.'materia'?>" class="btn btn-warning btn-large"> <i class="icon-leaf"></i> Variedades </a>
           <a href="<?php echo BASE_URL.'materia'?>" class="btn btn-warning btn-large"> <i class="icon-user"></i> Operarios </a>
    </div>
</div>
<!--end home-section-->