<div class="container-fluid">
<div class="row-fluid">
    <div class="span6">
        <div class="widget-content">
            <img src="<?php echo $_layoutParams['ruta_img']?>traube_logo.jpg" alt="" width="84%" >
        </div>
    </div>
    <div class="span6">
        <div class="widget-content">
            <img src="<?php echo $_layoutParams['ruta_img']?>john_deere_logo.jpg" alt="" width="60%" >
        </div>
    </div>
</div>